
---

# - name: Executing node
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/backend-app


- name: "Executing node"
  shell: |
    cd ~/backend-app
    npm install
    pm2 stop default
    pm2 start npm -- start