---
- name:  "Executing node"
  become: true
  apt:
    update_cache: yes

- name: "Executing node"
  become: true
  apt:
    upgrade: yes


- name: "Executing node"
  become: true
  apt:
    autoremove: yes

- name: "Executing node"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Executing node"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Executing node"
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Executing node"
  become: true
  shell: |
    pm2 stop all
    pm2 start npm -- start


- name:  start app
  command:  pm2 start main.js
  args:
    chdir: ~/backend/dist
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"